Repository kasecato/vscode-intellij-idea-keybindings, pull requests merged in 2023-08, with the labels that each got.

#293 Fix a bug which will cause failed
  src/importer/parser/IntelliJXmlParser.ts
Labels: bug

#301 Add support for `Use "CamelHumps" words`
  README.md
  package.json
  src/package-with-comment.json
Labels: enhancement

#305 Fixed #294 Keyboard layout-independent bindings
  package.json
  resource/default/Linux/VSCode.json
  resource/default/Mac/IntelliJ.xml
  resource/default/Mac/VSCode.json
  resource/default/Windows/VSCode.json
  src/package-with-comment.json
Labels: improvement
