Repository kasecato/vscode-intellij-idea-keybindings, pull requests merged in 2024-03, with the labels that each got.

#332 Improved #237 that Viewed file should be remembered
  package.json
  src/package-with-comment.json
Labels: improvement

#333 Add #239 that Support in Using Enter to Apply Code Suggestion
  package.json
  src/package-with-comment.json
Labels: enhancement

#338 Fixed #281 disabled insertLineAfter when notebook
  package.json
  src/package-with-comment.json
Labels: bug

#337 feat: Implement "Open in Opposite Group" command
  README.md
  package.json
  src/extension.ts
  src/importer/extension/IntellijExtension.ts
  src/package-with-comment.json
Labels: enhancement
